### PR TITLE
Update code for V2

### PR DESCRIPTION
**Pull request by KevinKrueger**

### CODE REVIEW

**Comment by gismofx** [comment]
Some good tweaks and clean up here. Thanks. 

I want to spend a little time going through it. Also, before I merge, I want to rename all instances of 'schedule' to 'event'.(I'm happy about this change, since everyone else calls it an 'event'! :) )

**Comment by KevinKrueger** [comment]
I tested it straight away. Works as expected.

No problem :)

**Comment by KevinKrueger** [comment]
I would like to open a better communication channel. What do you think of Slack? Or do you have another suggestion for better communication?

**Comment by gismofx** [comment]
Do you have the rendering issue?

**Comment by KevinKrueger** [comment]
I wanted to get your stand from the new branch first. But I can only do that if you merge, because otherwise I have to discard my commits.

**Pull request merged**
