### PR TITLE
Implementation of Time Zones

### PR DESCRIPTION
**Pull request by bbaileyHOM**
Hello,

I hope that this will meet with your approval!

Changes:
Added TUICalendarTimeZoneOption and TUITimeZone classes for serialization for time zones

Changed TUICalendarOptions property timezone to new time zone options class

Added TimeZones property to TUICalendarOptions for storing a list of TimeZoneInfo which will automatically populate the TUI time zones

### CODE REVIEW

**Comment by gismofx** [comment]
@bbaileyHOM this is great. Thanks for putting this together!

I have some thoughts and maybe think we should just juggle some code around. 

What do you think about moving all the functionality and logic for timezone out of `CalendarOptions`  and into of `TUITimeZone` class andor `TUICalendarTimeZoneOption`? This way there is only one "timezone" property to fill in the Options class. I think this is better for the user.

Seems like the TUICalendarTimeZoneOption class has some helpers/builders. My first thought was make 'ToTuiTimeZone'  a static method in `TUITimeZone` and rename.. For example:

`public static TUITimeZone.FromTimeZoneInfo(TimeZoneInfo timeZone, func<...., func<...... )`

I see how the helper funcs are useful, but do they need to be exposed as public properties? Would you mind sharing your usage example of the funcs in the sample project? 

Lastly, timezone property needs this attribute: 
`[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]`

Just some thoughts :) What do you think?

**Comment by gismofx** [comment]
> I removed the additional code from the main options class and put it most in the converter so it is tucked a bit more out of the way and I reduced the properties to just the one. I had those in there as simpler way for the serialization.
> 
> I also made the classes that serialize for the TUI Calendar private so that they aren't visible and are only for serialization.
> 
> The expression functions previously didn't need to be public, but now due as they are accessed by the JSON converter. I also put an example with the example project.
> 
> I added the conditional ignore attribute.
> 
> I'm not sure if I'm terribly happy with the JSON Converter as it seems unnecessarily complex. I had hoped to simply read in all the JSON and to just deserialize it as the private class, but I couldn't find a way to do that. I'm not sure there is really a case for deserializing anyway.

@bbaileyHOM Thanks. I agree...I would bring back the `TUITimezone` class so we don't need the custom serializer. Then we can convert a `TimeZoneInfo` into a TUITimeZone with a `AddTimeZoneInfo` helper method in `TUICalendarTimeZoneOption`

**Comment by gismofx** [comment]
@bbaileyHOM I made some changes to the PR to match what I was thinking above. It's closer to your original commit. I'm inclined to merge. Do you have any thoughts?

**Review by bbaileyHOM — COMMENTED** [review]
My only thought was that keeping a list of the time zones might be nice and a natural extension of that was to do so in the calendar, but the user can do that elsewhere of course.

I took a good look at the TUI documentation and it looks like their only way two ways to change them.  Either reinitialize the calendar setting the options that you want or to call setOptions with the options that you want so there isn't a dedicated way to change the time zones.

Is the design philosophy here to keep this as close to the TUI JavaScript design?  That seems reasonable and if so your approach is the best candidate.

**Comment by gismofx** [comment]
I think adding a helper function to add an Ienumerable of `TimeZoneInfo` could be ok. 

I prefer to keep the the connection between the two libraries clear. I know there are gaps like updating settings. In those cases, I think those should be added. 

Also, I want it to be "easy" to use so I'm all for improvements.

I think implementing setOptions will be very easy to do. Want to create an issue for it and I can work it?

**Comment by gismofx** [comment]
@bbaileyHOM  I'll merge this for now and we can continue to enhance the time zone options.

**Pull request merged**
